# Generated by Django 3.2.12 on 2023-11-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('course', models.CharField(choices=[('GU', 'Guitar'), ('PI', 'Piano'), ('VO', 'Vocal'), ('DR', 'Drum')], max_length=2)),
            ],
        ),
    ]
