# Generated by Django 3.2.12 on 2023-11-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
        ('schedule', '0002_alter_schedule_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturer.lecturer'),
        ),
    ]
