# Generated by Django 3.2.12 on 2023-11-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='lecturer',
        ),
    ]
